[toolchain]
#anchor_version = "v0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hip = "4DJBep6Jm34REZUnjr1NjEZiwqzm2pS1cjpiejvG2iUF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[build]
target = "bpfel-unknown-none"
toolchain = "nightly"


